---
- name: Terraform plan options (no apply)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tf_build: "ansible01"
    terraform_working_dir: /tmp/srv/
    terraform_state: present

    tf_project_dir: "{{ terraform_working_dir }}/aws"
    tf_var_file: "{{ tf_project_dir }}/terraform.tfvars"

    tf_workspace: "default"
    tf_plan_path: "{{ tf_project_dir }}/plan.tfplan"
    aap_password: "{{ lookup('ansible.builtin.env', 'AAP_PASSWORD') }}"

  tasks:
    
    - name: Clone Terraform Repo
      ansible.builtin.git:
        repo: 'https://github.com/taiseerhussein/terraform-files.git'
        version: main
        accept_newhostkey: true
        dest: "{{ terraform_working_dir }}"

    - name: Terraform plan (module in check mode)
      cloud.terraform.terraform:
        project_path: "{{ tf_project_dir }}"
        force_init: true
        workspace: "{{ tf_workspace }}"
        variables:
          aap_passwd: "{{ aap_password }}"
        variables_files:
          - "{{ tf_var_file }}"
        backend_config_files:
          - "{{ lookup('ansible.builtin.env', 'TF_BACKEND_CONFIG_FILE') }}"
      check_mode: true
      register: tf_plan
      tags: [plan_check]

    - name: Show command Ansible built (check-mode run)
      debug:
        var: tf_plan.command
      when: tf_plan is defined
      tags: [plan_check]

    